#!/bin/sh

# Set these paths appropriately

BIN=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/bin
CMD=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/cmd
LIB=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
