#!/bin/sh

# Set these paths appropriately

BIN=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/bin
CMD=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/cmd
LIB=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/estonian-abbreviations-utf8
PARFILE=${LIB}/estonian-utf8.par
MWLFILE=${LIB}/estonian-mwls-utf8

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

