#!/bin/sh

# Set these paths appropriately

BIN=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/bin
CMD=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/cmd
LIB=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
