#!/bin/sh

# Set these paths appropriately

BIN=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/bin
CMD=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/cmd
LIB=/home/vincent/Documents/Master_1/ECD/opinion-classifier/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
